const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/lichKhamBenh.controller');
const auth = require('../middlewares/auth.middleware');
const { loadMobileScope, guardResource, caregiverOnlyWrite } = require('../middlewares/mobile-scope.middleware');
router.use(auth);
router.use(loadMobileScope);
router.get('/',             ctrl.getAll);
router.post('/',            caregiverOnlyWrite, ctrl.create);
router.put('/:id',          caregiverOnlyWrite, guardResource('LichKhamBenh', 'LichKhamID'), ctrl.update);
router.patch('/:id/cancel', caregiverOnlyWrite, guardResource('LichKhamBenh', 'LichKhamID'), ctrl.cancel);
module.exports = router;
