const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/lienHeKhanCap.controller');
const auth = require('../middlewares/auth.middleware');
const { loadMobileScope, guardResource, caregiverOnlyWrite } = require('../middlewares/mobile-scope.middleware');
router.use(auth);
router.use(loadMobileScope);
router.get('/',    ctrl.getAll);
router.post('/',   caregiverOnlyWrite, ctrl.create);
router.put('/:id', caregiverOnlyWrite, guardResource('LienHeKhanCap', 'LienHeID'), ctrl.update);
router.delete('/:id', caregiverOnlyWrite, guardResource('LienHeKhanCap', 'LienHeID'), ctrl.remove);
module.exports = router;
