const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/nhatKyChamSoc.controller');
const auth = require('../middlewares/auth.middleware');
const { loadMobileScope, caregiverOnlyWrite } = require('../middlewares/mobile-scope.middleware');
router.use(auth);
router.use(loadMobileScope);
router.get('/',  ctrl.getAll);
router.post('/', caregiverOnlyWrite, ctrl.create);
router.patch('/:id', caregiverOnlyWrite,ctrl.update);
router.delete('/:id', caregiverOnlyWrite,ctrl.remove);
module.exports = router;
